name: Pipeline de Execucao - PR

on:
  pull_request:
    branches: ["main"]

jobs:
  RunTest:
    runs-on:  ubuntu-latest

    steps:

      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Instalar jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@v1.2.0
        with:
          chrome-version: latest

      - name: Instalar ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Rodar o teste
        run: mvn test -Dtest=RunCucumberTest -Dbrowser=chrome-ci

      - name: Gerar relatório
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: tests-report
          path: '**/formatedreport/'

      - name: Slack Notification - Success
          if: success()
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_COLOR: ${{ job.status }}
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_MESSAGE: 'Success on PR executions tests :white_check_mark:'
            SLACK_TITLE: 'Success on PR executions tests :white_check_mark:'
            SLACK_USERNAME: SUCCESS

      - name: Slack Notification - Failure
          if: failure()
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_COLOR: ${{ job.status }}
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_MESSAGE: 'Failure on PR executions tests :fire:'
            SLACK_TITLE: 'Failure on PR executions tests :fire:'
            SLACK_USERNAME: SUCCESS



